spring:
  datasource:
    url: jdbc:mysql://${MYSQLUSER}:${MYSQLPASSWORD}@${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/v1/like.*
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - expression: "getHeader('Authorization')"
          bandwidths:
            - capacity: 5
              time: 1
              unit: minutes

paypal:
  base-url: https://api-m.sandbox.paypal.com

cloudinary:
  url: cloudinary://145514162246859:-TrF50dJvtpBQMR28i4rpCIg5K4@nguyenhs
  folder: Herofund